name: Deploy CDK with Access Keys

on:
  push:
    branches:
      - layerswap

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1  # Change this to your region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CDK CLI
        run: npm install -g aws-cdk
    
      - name: Reconstruct .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        run: |
          echo "Configuring AWS credentials..."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Bootstrap CDK 
        run: |
            cdk bootstrap aws://$ACCOUNT_ID/$AWS_REGION
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION:  ${{ env.AWS_REGION }}
            ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          
      - name: Deploy CDK stack
        run: |
          cdk deploy RoutingAPIStack --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}