name: Deploy CDK to Dev Environment

on:
  push:
    branches:
      - layerswap-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install CDK CLI
        run: npm install -g aws-cdk
    
      - name: Reconstruct .env file
        run: |
          echo "${{ secrets.DEV_ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          npm ci
          npm run build
    
      - name: Bootstrap CDK (Dev)
        run: |
            cdk bootstrap aws://${{ secrets.DEV_AWS_ACCOUNT_ID }}/eu-west-1
          
      - name: Deploy CDK stack to Dev
        run: |
          cdk deploy RoutingAPIStackDev --require-approval never
